# Generated by Django 5.0 on 2024-09-12 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=60)),
                ('contents', models.JSONField(blank=True, default=list)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.doctor')),
                ('registeredStudents', models.ManyToManyField(blank=True, related_name='students', to='register.student')),
            ],
        ),
    ]
