# Generated by Django 5.0 on 2024-09-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='registeredStudents',
            field=models.ManyToManyField(blank=True, related_name='courses', to='register.student'),
        ),
    ]
