# Generated by Django 5.1.1 on 2024-09-12 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_registeredstudents'),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='register.doctor'),
        ),
    ]
