# Generated by Django 5.1.1 on 2024-09-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='latestPage',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
