# Generated by Django 5.1.1 on 2024-09-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='courseRequest',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
